=== m4rocks/paquet/app-spec-schema.json
{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"$schema":{"type":"string"},"id":{"type":"string","minLength":1,"maxLength":50,"pattern":"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"},"url":{"type":"string","format":"uri"},"manifestUrl":{"type":"string","format":"uri"},"features":{"type":"array","items":{"type":"string","enum":["open-source","mobile","desktop","auth","offline","data-collection"]}},"githubUrl":{"type":"string","format":"starts_with","pattern":"^https:\\/\\/github\\.com\\/.*"},"gitlabUrl":{"type":"string","format":"starts_with","pattern":"^https:\\/\\/gitlab\\.com\\/.*"},"syncGitHubReleases":{"type":"boolean"},"privacyPolicyUrl":{"type":"string","format":"uri"},"termsAndConditionsUrl":{"type":"string","format":"uri"},"categories":{"type":"array","items":{"type":"string","enum":["news","social","chat","messenger","messaging","entertainment","video","movies","tv","streaming","utilities","tool","tools","utility","productivity","work","business","office","education","games","game","gaming","music","audio","sound","development","code","coding","program","programming","developer","developers","lifestyle","photo","travel","trip","health","books"]}},"author":{"type":"string","minLength":1,"maxLength":30},"authorUrl":{"type":"string","format":"uri"},"accentColor":{"type":"string"},"updatedDate":{"type":"string","format":"date","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"}},"required":["$schema","id","url","features","author","updatedDate"],"additionalProperties":false}

=== m4rocks/paquet/apps/dev.vscode.insiders.json
{
	"$schema": "../app-spec-schema.json",
	"id": "dev.vscode.insiders",
	"url": "https://insiders.vscode.dev",
	"manifestUrl": "https://insiders.vscode.dev/static/insider/code.webmanifest",
	"features": [
		"desktop",
		"offline",
		"open-source"
	],
	"githubUrl": "https://github.com/microsoft/vscode",
	"categories": [
		"development"
	],
	"termsAndConditionsUrl": "https://www.microsoft.com/en-us/legal/terms-of-use",
	"privacyPolicyUrl": "https://www.microsoft.com/en-gb/privacy/privacystatement",
	"author": "Microsoft",
	"authorUrl": "https://microsoft.com/",
	"accentColor": "#0eb49c",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/com.journalisticapp.pwa.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.journalisticapp.pwa",
	"url": "https://pwa.journalisticapp.com",
	"manifestUrl": "https://pwa.journalisticapp.com/manifest.json",
	"features": [
		"desktop",
		"mobile",
		"auth",
		"data-collection"
	],
	"categories": [
		"lifestyle"
	],
	"termsAndConditionsUrl": "https://journalisticapp.com/terms",
	"privacyPolicyUrl": "https://journalisticapp.com/privacy",
	"author": "Journalistic",
	"accentColor": "#7f7f7f",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/com.appspot.guitar-tuner.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.appspot.guitar-tuner",
	"url": "https://guitar-tuner.appspot.com/",
	"manifestUrl": "https://guitar-tuner.appspot.com/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"offline",
		"open-source"
	],
	"githubUrl": "https://github.com/googlearchive/guitar-tuner",
	"categories": [
		"utilities"
	],
	"author": "Paul Lewis",
	"accentColor": "#efb90f",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/com.spotify.open.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.spotify.open",
	"url": "https://open.spotify.com",
	"manifestUrl": "https://open.spotifycdn.com/cdn/generated/manifest-mobile-web-player.a1ddf51c.json",
	"features": [
		"mobile",
		"desktop",
		"auth"
	],
	"categories": [
		"music"
	],
	"termsAndConditionsUrl": "https://spotify.com/us/legal/end-user-agreement/",
	"privacyPolicyUrl": "https://spotify.com/us/legal/privacy-policy/",
	"author": "Spotify",
	"authorUrl": "https://spotify.com",
	"accentColor": "#1cd363",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/dev.vscode.json
{
	"$schema": "../app-spec-schema.json",
	"id": "dev.vscode",
	"url": "https://vscode.dev",
	"manifestUrl": "https://vscode.dev/static/stable/code.webmanifest",
	"features": [
		"desktop",
		"offline",
		"open-source"
	],
	"githubUrl": "https://github.com/microsoft/vscode",
	"categories": [
		"development"
	],
	"termsAndConditionsUrl": "https://www.microsoft.com/en-us/legal/terms-of-use",
	"privacyPolicyUrl": "https://www.microsoft.com/en-gb/privacy/privacystatement",
	"author": "Microsoft",
	"authorUrl": "https://microsoft.com/",
	"accentColor": "#24adf4",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/com.google.santatracker.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.google.santatracker",
	"url": "https://santatracker.google.com",
	"manifestUrl": "https://santatracker.google.com/manifest.json",
	"features": [
		"desktop",
		"mobile",
		"data-collection"
	],
	"termsAndConditionsUrl": "https://policies.google.com/terms",
	"privacyPolicyUrl": "https://policies.google.com/privacy",
	"categories": [
		"games"
	],
	"author": "Google",
	"accentColor": "#e13d34",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/io.github.nenadalm.player-order-selector.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.nenadalm.player-order-selector",
	"url": "https://nenadalm.github.io/player-order-selector/",
	"author": "Miloslav Nenad√°l",
	"manifestUrl": "https://nenadalm.github.io/player-order-selector/manifest.json",
	"features": [
		"open-source",
		"mobile",
		"offline"
	],
	"categories": ["games"],
	"githubUrl": "https://github.com/nenadalm/player-order-selector",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/io.github.matthijsgroen.block-sort.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.matthijsgroen.block-sort",
	"url": "https://matthijsgroen.github.io/block-sort/",
	"author": "Matthijs Groen",
	"manifestUrl": "https://matthijsgroen.github.io/block-sort/manifest.webmanifest",
	"features": [
		"open-source",
		"mobile",
		"desktop",
		"offline"
	],
	"categories": ["games"],
	"githubUrl": "https://github.com/matthijsgroen/block-sort",
	"updatedDate": "2025-04-16"
}
