=== m4rocks/paquet/app-spec-schema.json
{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"$schema":{"type":"string"},"id":{"type":"string","minLength":1,"maxLength":50,"pattern":"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"},"url":{"type":"string","format":"uri"},"manifestUrl":{"type":"string","format":"uri"},"features":{"type":"array","items":{"type":"string","enum":["open-source","mobile","desktop","auth","offline","data-collection"]}},"githubUrl":{"type":"string","format":"starts_with","pattern":"^https:\\/\\/github\\.com\\/.*"},"gitlabUrl":{"type":"string","format":"starts_with","pattern":"^https:\\/\\/gitlab\\.com\\/.*"},"syncGitHubReleases":{"type":"boolean"},"privacyPolicyUrl":{"type":"string","format":"uri"},"termsAndConditionsUrl":{"type":"string","format":"uri"},"categories":{"type":"array","items":{"type":"string","enum":["news","social","chat","messenger","messaging","entertainment","video","movies","tv","streaming","utilities","tool","tools","utility","productivity","work","business","office","education","games","game","gaming","music","audio","sound","development","code","coding","program","programming","developer","developers","lifestyle","photo","travel","trip","health","books"]}},"author":{"type":"string","minLength":1,"maxLength":30},"authorUrl":{"type":"string","format":"uri"},"accentColor":{"type":"string"},"updatedDate":{"type":"string","format":"date","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"}},"required":["$schema","id","url","features","author","updatedDate"],"additionalProperties":false}

=== m4rocks/paquet/apps/com.tiktok.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.tiktok",
	"url": "https://tiktok.com",
	"manifestUrl": "https://tiktok.com/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"social",
		"entertainment"
	],
	"privacyPolicyUrl": "https://www.tiktok.com/legal/page/us/privacy-policy/en",
	"termsAndConditionsUrl": "https://www.tiktok.com/legal/page/us/terms-of-service/en",
	"author": "ByteDance",
	"accentColor": "#24f3eb",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/com.boxy-svg.app.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.boxy-svg.app",
	"url": "https://boxy-svg.com/app",
	"manifestUrl": "https://boxy-svg.com/boxy-svg.webmanifest",
	"features": [
		"desktop",
		"offline"
	],
	"categories": [
		"lifestyle"
	],
	"privacyPolicyUrl": "https://boxy-svg.com/legal/web-privacy",
	"termsAndConditionsUrl": "https://boxy-svg.com/legal/web-terms",
	"author": "Jaros≈Çaw Foksa",
	"accentColor": "#fbbb4c",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/eu.mconverter.json
{
	"$schema": "../app-spec-schema.json",
	"id": "eu.mconverter",
	"url": "https://mconverter.eu",
	"manifestUrl": "https://mconverter.eu/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"utilities",
		"lifestyle",
		"entertainment"
	],
	"author": "MConverter",
	"accentColor": "#5494fc",
	"updatedDate": "2025-04-15"
}

=== m4rocks/paquet/apps/app.web.othello-rust.json
{
	"$schema": "../app-spec-schema.json",
	"id": "app.web.othello-rust",
	"url": "https://othello-rust.web.app/",
	"manifestUrl": "https://othello-rust.web.app/manifest.webmanifest",
	"features": [
		"open-source",
		"mobile",
		"desktop",
		"offline"
	],
	"categories": ["games"],
	"githubUrl": "https://github.com/nstringham/othello-web-app",
	"author": "Nate Stringham",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/rocks.m4.paquet.json
{
	"$schema": "../app-spec-schema.json",
	"id": "rocks.m4.paquet",
	"author": "m4rocks",
	"githubUrl": "https://github.com/m4rocks/paquet",
	"features": ["desktop", "mobile", "open-source"],
	"termsAndConditionsUrl": "https://paquet.m4.rocks/terms-and-conditions",
	"privacyPolicyUrl": "https://paquet.m4.rocks/privacy",
	"authorUrl": "https://m4.rocks",
	"url": "https://paquet.m4.rocks",
	"updatedDate": "2025-04-14"
}

=== m4rocks/paquet/apps/com.instagram.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.instagram",
	"url": "https://www.instagram.com",
	"manifestUrl": "https://www.instagram.com/data/manifest.json/",
	"features": [
		"mobile",
		"desktop",
		"auth"
	],
	"categories": [
		"social"
	],
	"author": "Meta",
	"accentColor": "#c43c7c",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/com.youtube.music.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.youtube.music",
	"url": "https://music.youtube.com/",
	"manifestUrl": "https://music.youtube.com/manifest.webmanifest",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"entertainment",
		"music"
	],
	"author": "YouTube",
	"accentColor": "#fc0404",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/app.web.wallpeppers.json
{
	"$schema": "../app-spec-schema.json",
	"id": "app.web.wallpeppers",
	"url": "https://wallpeppers.web.app",
	"manifestUrl": "https://wallpeppers.web.app/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"open-source"
	],
	"categories": [
		"lifestyle",
		"utilities"
	],
	"author": "undefyned",
	"accentColor": "#fc9504",
	"updatedDate": "2025-04-16"
}
