=== m4rocks/paquet/app-spec-schema.json
{"$schema":"https://json-schema.org/draft/2020-12/schema","type":"object","properties":{"$schema":{"type":"string"},"id":{"type":"string","minLength":1,"maxLength":50,"pattern":"^[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?$"},"url":{"type":"string","format":"uri"},"manifestUrl":{"type":"string","format":"uri"},"features":{"type":"array","items":{"type":"string","enum":["open-source","mobile","desktop","auth","offline","data-collection"]}},"githubUrl":{"type":"string","format":"starts_with","pattern":"^https:\\/\\/github\\.com\\/.*"},"gitlabUrl":{"type":"string","format":"starts_with","pattern":"^https:\\/\\/gitlab\\.com\\/.*"},"syncGitHubReleases":{"type":"boolean"},"privacyPolicyUrl":{"type":"string","format":"uri"},"termsAndConditionsUrl":{"type":"string","format":"uri"},"categories":{"type":"array","items":{"type":"string","enum":["news","social","chat","messenger","messaging","entertainment","video","movies","tv","streaming","utilities","tool","tools","utility","productivity","work","business","office","education","games","game","gaming","music","audio","sound","development","code","coding","program","programming","developer","developers","lifestyle","photo","travel","trip","health","books"]}},"author":{"type":"string","minLength":1,"maxLength":30},"authorUrl":{"type":"string","format":"uri"},"accentColor":{"type":"string"},"updatedDate":{"type":"string","format":"date","pattern":"^(?:(?:\\d\\d[2468][048]|\\d\\d[13579][26]|\\d\\d0[48]|[02468][048]00|[13579][26]00)-02-29|\\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\\d|30)|(?:02)-(?:0[1-9]|1\\d|2[0-8])))$"}},"required":["$schema","id","url","features","author","updatedDate"],"additionalProperties":false}

=== m4rocks/paquet/apps/com.google.maps.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.google.maps",
	"url": "https://google.com/maps",
	"manifestUrl": "https://google.com/maps/preview/pwa/manifest",
	"features": [
		"mobile",
		"desktop",
		"data-collection"
	],
	"termsAndConditionsUrl": "https://policies.google.com/terms",
	"privacyPolicyUrl": "https://policies.google.com/privacy",
	"categories": [
		"lifestyle"
	],
	"author": "Google",
	"accentColor": "#fbbb05",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/app.screenrecorderweb.json
{
	"$schema": "../app-spec-schema.json",
	"id": "app.screenrecorderweb",
	"url": "https://screenrecorderweb.app",
	"manifestUrl": "https://screenrecorderweb.app/manifest.json",
	"features": [
		"desktop",
		"offline",
		"open-source"
	],
	"githubUrl": "https://github.com/carsonsaldanha/screen-recorder",
	"categories": [
		"utilities"
	],
	"author": "Carson Saldanha",
	"accentColor": "#c4241c",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/com.google.travel.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.google.travel",
	"url": "https://www.google.com/travel",
	"manifestUrl": "https://www.google.com/_/TravelFrontendUi/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"lifestyle"
	],
	"author": "Google",
	"accentColor": "#fabc05",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/com.monkeytype.json
{
	"$schema": "../app-spec-schema.json",
	"id": "com.monkeytype",
	"url": "https://monkeytype.com",
	"manifestUrl": "https://monkeytype.com/manifest.json",
	"features": [
		"open-source",
		"desktop",
		"mobile",
		"offline"
	],
	"githubUrl": "https://github.com/monkeytypegame/monkeytype",
	"categories": [
		"utilities",
		"games"
	],
	"termsAndConditionsUrl": "https://monkeytype.com/terms-of-service",
	"privacyPolicyUrl": "https://monkeytype.com/privacy-policy",
	"author": "Miodec",
	"accentColor": "#dcb015",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/io.github.nenadalm.life-counter.json
{
	"$schema": "../app-spec-schema.json",
	"id": "io.github.nenadalm.life-counter",
	"url": "https://nenadalm.github.io/life-counter/",
	"author": "Miloslav Nenad√°l",
	"manifestUrl": "https://nenadalm.github.io/life-counter/manifest.json",
	"features": [
		"open-source",
		"mobile",
		"offline"
	],
	"categories": ["games"],
	"githubUrl": "https://github.com/nenadalm/life-counter",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/site.esstudio.newsfeeder.json
{
	"$schema": "../app-spec-schema.json",
	"id": "site.esstudio.newsfeeder",
	"url": "https://newsfeeder.esstudio.site",
	"manifestUrl": "https://newsfeeder.esstudio.site/manifest.json",
	"features": [
		"mobile",
		"desktop"
	],
	"categories": [
		"news"
	],
	"author": "Sem Postma",
	"accentColor": "#f45c3d",
	"updatedDate": "2025-04-08"
}

=== m4rocks/paquet/apps/dev.daily.app.json
{
	"$schema": "../app-spec-schema.json",
	"id": "dev.daily.app",
	"url": "https://app.daily.dev",
	"manifestUrl": "https://app.daily.dev/manifest.json",
	"features": [
		"mobile",
		"desktop",
		"open-source"
	],
	"githubUrl": "https://github.com/dailydotdev/daily",
	"categories": [
		"news",
		"development"
	],
	"termsAndConditionsUrl": "https://daily.dev/tos",
	"privacyPolicyUrl": "https://daily.dev/privacy/applications-policy",
	"author": "daily.dev",
	"accentColor": "#448cfc",
	"updatedDate": "2025-04-16"
}

=== m4rocks/paquet/apps/app.webappfinder.json
{
	"$schema": "../app-spec-schema.json",
	"id": "app.webappfinder",
	"url": "https://webappfinder.app",
	"manifestUrl": "https://webappfinder.app/manifest.webmanifest",
	"features": [
		"mobile",
		"desktop",
		"offline",
		"open-source"
	],
	"githubUrl": "https://github.com/kromans11-gmail/kromans11-gmail.github.io",
	"categories": [
		"utilities"
	],
	"author": "Kent",
	"authorUrl": "https://webappfinder.app",
	"accentColor": "#4f46e5",
	"updatedDate": "2026-07-07"
}
